[build]
  publish = "dist"
  command = "cp package-netlify.json package.json && npm install && npx vite build --config vite.config.netlify.ts"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"